### ISSUE TITLE
Feature request: expose a service that allows toggling of zones

### ISSUE THREAD

**Issue by bremor** [bremor/bonaire_myclimate#8]
```
service: bonaire_myclimate.turn_zone_off
data:
  entity_id: bonaire_myclimate
  zone: 1

service: bonaire_myclimate.turn_zone_on
data:
  entity_id: bonaire_myclimate
  zone: 1
```
