### ISSUE TITLE
Feature request: Support naming of zones

### ISSUE THREAD

**Issue by bremor** [bremor/bonaire_myclimate#9]
```
climate:
  - platform: 'bonaire_myclimate'
  - zone_names:
    - 1: Downstairs
    - 2: Upstairs
```
